# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunSee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FunSee

  target 'FunSeeTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh'
pod 'Masonry'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'CLPlayer'
end
